### ISSUE TITLE
use proper staging domain

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/projects_website#76]
https://staging2.consciousinternet.freeflowpages.com this is not right to use

**Comment by Hamdy** [comment]
@xmonader we have working https://staging.consciousinternet.org/
https://staging2.consciousinternet.freeflowpages.com is just a development machine , easier to be accessed by UI team since it can be accessed directly without zero-tier

production and staging machines are supported by flist deployment mechanism
and have proper  deployment docs in the appropriate repos
